"""Public P5 reasoning-control contracts for CyberSecGPT."""

from .budget import (
    ReasoningBudget,
    ReasoningBudgetDelta,
    ReasoningBudgetDimension,
    ReasoningBudgetExceededError,
    ReasoningBudgetUsage,
    consume_reasoning_budget,
    exhausted_reasoning_budget_dimensions,
)
from .errors import (
    BrainRequestError,
    ReasoningBudgetError,
    ReasoningError,
    ReasoningLifecycleError,
    RoutingDecisionError,
    RoutingDecisionValidationError,
    RoutingReasoningBudgetError,
    SubstrateDiscoveryError,
)
from .lifecycle import (
    ReasoningLifecycleSnapshot,
    ReasoningState,
    begin_reasoning_lifecycle,
    transition_reasoning_state,
)
from .request import BrainRequest, admit_brain_request
from .routing import (
    RoutingDecision,
    RoutingDecisionInvalidReason,
    RoutingDecisionReasonCode,
    RoutingDecisionValidation,
    RoutingReasoningBudgetUsage,
    begin_routing_reasoning_budget,
    consume_routing_reasoning_budget,
    validate_routing_decision,
)
from .substrates import (
    CapabilitySnapshot,
    SubstrateAvailabilityState,
    SubstrateDescriptor,
    SubstrateKind,
    SubstrateProvenance,
    SubstrateResourceProfile,
    SubstrateValidationEvidence,
    ValidatedSubstrate,
    build_capability_snapshot,
    validate_substrate_descriptor,
)

__all__ = [
    "ReasoningError",
    "BrainRequestError",
    "BrainRequest",
    "admit_brain_request",
    "SubstrateDiscoveryError",
    "SubstrateKind",
    "SubstrateAvailabilityState",
    "SubstrateResourceProfile",
    "SubstrateProvenance",
    "SubstrateDescriptor",
    "SubstrateValidationEvidence",
    "ValidatedSubstrate",
    "CapabilitySnapshot",
    "validate_substrate_descriptor",
    "build_capability_snapshot",
    "ReasoningBudgetError",
    "ReasoningBudgetExceededError",
    "ReasoningBudget",
    "ReasoningBudgetDelta",
    "ReasoningBudgetDimension",
    "ReasoningBudgetUsage",
    "consume_reasoning_budget",
    "exhausted_reasoning_budget_dimensions",
    "ReasoningLifecycleError",
    "ReasoningLifecycleSnapshot",
    "ReasoningState",
    "begin_reasoning_lifecycle",
    "transition_reasoning_state",
    "RoutingReasoningBudgetError",
    "RoutingReasoningBudgetUsage",
    "begin_routing_reasoning_budget",
    "consume_routing_reasoning_budget",
    "RoutingDecisionError",
    "RoutingDecisionValidationError",
    "RoutingDecision",
    "RoutingDecisionInvalidReason",
    "RoutingDecisionReasonCode",
    "RoutingDecisionValidation",
    "validate_routing_decision",
]
