"""Tests for the conservative public Reasoning API."""

import cybersecgpt.reasoning as reasoning


def test_public_api_is_explicit() -> None:
    assert reasoning.__all__ == [
        "ReasoningError",
        "BrainRequestError",
        "BrainRequest",
        "admit_brain_request",
        "SubstrateDiscoveryError",
        "SubstrateKind",
        "SubstrateAvailabilityState",
        "SubstrateResourceProfile",
        "SubstrateProvenance",
        "SubstrateDescriptor",
        "SubstrateValidationEvidence",
        "ValidatedSubstrate",
        "CapabilitySnapshot",
        "validate_substrate_descriptor",
        "build_capability_snapshot",
        "CandidateSelectionError",
        "CandidateRejectionReason",
        "CandidateSelectionPolicy",
        "CandidateEvaluation",
        "CandidateSelectionResult",
        "select_candidate_substrates",
        "FallbackReplanError",
        "FallbackTrigger",
        "FallbackReplanStatus",
        "FallbackReplanPolicy",
        "FallbackReplanResult",
        "replan_fallback_route",
        "ReasoningBudgetError",
        "ReasoningBudgetExceededError",
        "ReasoningBudget",
        "ReasoningBudgetDelta",
        "ReasoningBudgetDimension",
        "ReasoningBudgetUsage",
        "consume_reasoning_budget",
        "exhausted_reasoning_budget_dimensions",
        "ReasoningLifecycleError",
        "ReasoningLifecycleSnapshot",
        "ReasoningState",
        "begin_reasoning_lifecycle",
        "transition_reasoning_state",
        "RoutingReasoningBudgetError",
        "RoutingReasoningBudgetUsage",
        "begin_routing_reasoning_budget",
        "consume_routing_reasoning_budget",
        "RoutingDecisionError",
        "RoutingDecisionValidationError",
        "RoutingDecision",
        "RoutingDecisionInvalidReason",
        "RoutingDecisionReasonCode",
        "RoutingDecisionValidation",
        "validate_routing_decision",
        "TerminationPropagationError",
        "TerminationReason",
        "TerminationTargetKind",
        "TerminationAcknowledgementState",
        "TerminationPropagationStatus",
        "TerminationRequirement",
        "TerminationTarget",
        "TerminationAcknowledgement",
        "TerminationPropagation",
        "TerminationPropagationEvaluation",
        "evaluate_termination_requirement",
        "begin_termination_propagation",
        "acknowledge_termination_target",
        "evaluate_termination_propagation",
    ]
    assert all(hasattr(reasoning, name) for name in reasoning.__all__)
